### ISSUE TITLE
Memory lack! with Tensorflow oom on GPU

### ISSUE THREAD

**Issue by raha2007** [habrman/FaceRecognition#10]
@habrman !
First, thank you very much for your nice project and the guidance, everything work well for me.

Then, I faced a problem with huge number of subjects due to the lack of memory. My GPU supports 8 GB memory but I faced error "GPU Memory Allocation" when I use 2000+ subjects of LFW.
I found that I have to decrease the batch_size of the data in the network to use smaller parts of memory allocations but I am not sure where you learn.

here is the line that I received error
`
self.embeddings = sess.run(embeddings, feed_dict=feed_dict)
`
Could you please help me to solve it?
Thank you in advance

**Comment by habrman** [comment]
Hi,

First of all, sorry for such a late response but I think you misunderstand the purpose of this repo. I never learn anything. It's more of a showcase repo to show what the model is capable of and I only use a pretrained model to run inference. Please check the readme for links to the code for training. However, reducing the batch size is a good solution to make this code work with a large number of identities. I'm not sure about if you manage to do this by yourself or if you need help to do it?
