### ISSUE TITLE
Wrong Recognition of Faces

### ISSUE THREAD

**Issue by guruvishnuvardan** [habrman/FaceRecognition#11]
Hi Habrman,

I am testing this algorithm for my research purpose for the past 5 months, sometimes i see wrong faces are  recognised(Example: Face ID: A is Recognised as Face ID:B) or Similar Bald Persons are wrongly recognised. 

I have increased the threshold to **threshold = [0.8, 0.7, 0.7]**, inspite of this, I do get false recognition's, Can you please suggest me few other ways to increase the detection rate

Thanks
Guru

**Comment by habrman** [comment]
Short solution summary: You should decrease the threshold, not increase, to minimize the risk of false classifications. Adding more images to an id will help as well. Finally it could help to upgrade your camera if you have a low resolution/quality camera and make sure that the detected faces are large. 

Long answer: The model is not perfect and wrong classifications can happen. One reason could be that the images you provide to the model differ from the distribution in the dataset. The faces are found in each frame and a crop is extracted. The crop is then resized to fit the model. If you have a low resolution and/or quality webcam or if the face crop is small the crop will look bad and very different from the dataset which makes it difficult to classify. What's happening is that an embedding from id A ends up close to the embeddings of the provided images of id B. Lowering the threshold will require a shorter distance between two embeddings which makes it more difficult to find a match. By adding more images to an id you will provide more measurement points for each id which in turn makes it easier to find a match for that id.

Let me know if you have any more questions but for now I'll close this issue.

**Comment by guruvishnuvardan** [comment]
Thanks Habrman. I will follow your advice. 

I will upgrade the camera to a verifocal zoom camera, so that the faces look bigger and also I have reduced thresold to **threshold = [0.5, 0.6, 0.6]**

Can I use 100 different classes(with close to 50 different images in each) to recognise faces, off course, I will use a 1080 TI GPU to process the images.

**Comment by habrman** [comment]
Sure, that should be fine. You might need to change the batch size to fit your memory with that many images.

If you're really serious you should create your own dataset and train the model on it. This will probably give you a big improvement boost but it can take quite some time.

**Comment by guruvishnuvardan** [comment]
Can you please share me, If you have any reference code to train face images?

**Comment by guruvishnuvardan** [comment]
Thanks Habrman.

**Comment by guruvishnuvardan** [comment]
Hi Habrman,

I have my own dataset of faces, Can you please share me any link, to train my custom face recognition dataset.

Thanks
Guru
