### ISSUE TITLE
Doesn't run on OSX Mojave 10.14.2

### ISSUE THREAD

**Issue by BetterRobotics** [habrman/FaceRecognition#12]
Folder setup:
└── FaceRecognition
├── 20170512-110547
 │   ├── 20170512-110547.pb
 │   ├── model-20170512-110547.ckpt-250000.data-00000-of-00001
 │   ├── model-20170512-110547.ckpt-250000.index
 │   └── model-20170512-110547.meta
├── LICENSE
├── README.md
├── pycache
 │   └── detect_and_align.cpython-37.pyc
├── det1.npy
├── det2.npy
├── det3.npy
├── detect_and_align.py
├── example.png
├── ids
 │   ├── Ben
 │    │   ├── Ben0.png
 │    │   └── Ben1.jpg
 │   └── James
 │   └── James0.jpg
└── main.py

Error

bunker$ python3 main.py ./20170512-110547/20170512-110547.pb ./ids/
ARGS: Namespace(id_folder=['./ids/'], model='./20170512-110547/20170512-110547.pb', threshold=1.2)
Loading model filename: ./20170512-110547/20170512-110547.pb
graph
Traceback (most recent call last):
File "main.py", line 188, in 
main(parser.parse_args())
File "main.py", line 102, in main
load_model(args.model)
File "main.py", line 90, in load_model
tf.import_graph_def(graph_def, name='')
File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/importer.py", line 258, in import_graph_def
op_def = op_dict[node.op]
KeyError: 'FIFOQueueV2'

**Comment by BetterRobotics** [comment]
**Folder setup:**

  '└── FaceRecognition
   ├── 20170512-110547
    │   ├── 20170512-110547.pb
    │   ├── model-20170512-110547.ckpt-250000.data-00000-of-00001
    │   ├── model-20170512-110547.ckpt-250000.index
    │   └── model-20170512-110547.meta
    ├── LICENSE
    ├── README.md
    ├── __pycache__
    │   └── detect_and_align.cpython-37.pyc
    ├── det1.npy
    ├── det2.npy
    ├── det3.npy
    ├── detect_and_align.py
    ├── example.png
    ├── ids
    │   ├── Ben
    │   │   ├── Ben0.png
    │   │   └── Ben1.jpg
    │   └── James
    │       └── James0.jpg
    └── main.py'


**Error**

'bunker$ python3 main.py ./20170512-110547/20170512-110547.pb ./ids/
ARGS: Namespace(id_folder=['./ids/'], model='./20170512-110547/20170512-110547.pb', threshold=1.2)
Loading model filename: ./20170512-110547/20170512-110547.pb
graph
Traceback (most recent call last):
  File "main.py", line 188, in <module>
    main(parser.parse_args())
  File "main.py", line 102, in main
    load_model(args.model)
  File "main.py", line 90, in load_model
    tf.import_graph_def(graph_def, name='')
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/importer.py", line 258, in import_graph_def
    op_def = op_dict[node.op]
KeyError: 'FIFOQueueV2'

'

**Comment by habrman** [comment]
This is not related to your os. It's an error from tensorflow and it means that the model you're using is not compatible with your version of tensorflow. You could try and find a different model that's compatible with your current tensorflow or install a different tensorflow version.

Here's an issue from the repo that trained the model I'm referencing.
https://github.com/davidsandberg/facenet/issues/284

**Comment by BetterRobotics** [comment]
Thanks Harman, 

I managed to get it working with TF 1.12.0 using this command 

`pip3 install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.12.0-py3-none-any.whl`
