### ISSUE TITLE
Save and load embeddings

### ISSUE THREAD

**Issue by Rasoul20sh** [habrman/FaceRecognition#15]
Hi @habrman  and thanks for sharing your code.
As my database includes a number of images I want to get rid of making embeddings every time. 
I tested saving and loading embeddings using this syntax:
```
#for saving:
np.save('embeddings.npy' , self.embeddings)
#for loading
self.embeddings = np.load('embeddings.npy')
```
in the **IdData Class**.
but it leads to error:

`IndexError: list index out of range
`

**Comment by habrman** [comment]
Could you please post the full error message?

**Comment by Rasoul20sh** [comment]
Thanks @habrman for your reply. It solved. I should save both self.embeddings and self.id_names.
Now I can load hundereds of embeddings in a few secconds.

**Comment by Rasoul20sh** [comment]
Thanks @habrman for your reply. It solved. I should save both self.embeddings and self.id_names.
Now I can load hundereds of embeddings in a few secconds.
