### ISSUE TITLE
how to train pic to match face id and use mtcnn which features to detect  

### ISSUE THREAD

**Issue by hsm4703** [habrman/FaceRecognition#17]

**Comment by hsm4703** [comment]
this can see five points in face eyes nose and lip  can you tell me  according to What characteristics to match

**Comment by hsm4703** [comment]
because i use my images to use your model to run your code  
but i have two quesions 
1. why use 1 pic if i use 10spics or more pics  can up Correct identification?  
2.i try to use now opencv face 68 features points to change your 5 features points to up Recognition rate, am i?

**Comment by habrman** [comment]
1. Yes. Using multiple images will make it more stable and improve accuracy
2. The number of facial features have nothing to do with the id matching. It's only used to find faces in images. If you find that opencv is better suitable for your images you can use it, just make sure to use the same alignment and normalisation that is used in my code.

**Comment by hsm4703** [comment]
can you tell me 5 face landmark  68 landmark Individual advantages  which performance good or tell me each advantages  thanks :)

**Comment by hsm4703** [comment]
Excuse me, how can I change the five-point feature to 68 points?
Can tell me a little bit about where to change

**Comment by habrman** [comment]
As I said the number of landmarks don't matter for the id matching. What matters is if you manage to find the faces at all. If you find all the faces with mtcnn there's no need to change and if you don't you could always try openCV to see if it improves. If you for some reason want more than the 5 landmarks you get from mtcnn you could of course change to openCV as long as you're not missing detections.

https://github.com/habrman/FaceRecognition/blob/3b729f73a35ad68b9067d498fa29b74bc15cd486/detect_and_align.py#L13
That's the line that detects faces and landmarks. You could change that to you own function that uses openCV instead but you need to make sure that the output of your function has the same format as the output of `detect_face`.
