### ISSUE TITLE
How to load model and images in this project

### ISSUE THREAD

**Issue by anandpanchal800** [habrman/FaceRecognition#24]
Please author help me to run this program, I'm trying to learn something from your work but somehow I cannot able run this program. it gives me this error 

"usage: main.py [-h] [-t THRESHOLD] model id_folder [id_folder ...]
main.py: error: the following arguments are required: model, id_folder"

please anybody help me :(

**Comment by geezz02** [comment]
You need to enter this code in your virtual environment (TensorFlow):**cd C:\Users\Dell\Desktop\ Facerecognition-master\Facerecognition-master (change it to your path)**,then enter:**python main.py ./20170512-110547/20170512-110547/20170512-110547.pb ./ids/(change it to your path)**
![image](https://user-images.githubusercontent.com/74125927/113662874-8ea34100-96db-11eb-8e90-37802dca9059.png)

**Comment by habrman** [comment]
As mentioned above you need to pass the model and a directory with images. There are more detailed instructions in the readme. The structure of the directory with images is very important so make sure you get it right.
