### ISSUE TITLE
Where does code be used to recognition in file detect_facese_real_time.py ? 

### ISSUE THREAD

**Issue by mactiendinh** [habrman/FaceRecognition#5]
And Where does code be used Facenet algorithm to recognition in file detect_facese_real_time.py ? Does you use file detect_facese_real_time.py only detect ?
Thank you !!!

**Comment by habrman** [comment]
`detect_facese_real_time.py` does not exist. Assuming that you mean `detect_and_align.py` you have 3 questions:

1. The function `align_image` in `detect_and_align.py` finds faces and facial landmarks in an image.

2. I'm using Inception Resnet and not Facenet but the usage is the same so it doesn't really matter. It's not used in `detect_and_align.py`. Instead you use it by calling these lines:
```
feed_dict = {images_placeholder: face_patches, phase_train_placeholder: False}
embs = sess.run(embeddings, feed_dict=feed_dict)
```
The embeddings that come out can then be seen as multidimensional points. If 2 points are close to each other they correspond to the same person.

3. `detect_facese_real_time.py` is only used to detect faces and landmarks
