### ISSUE TITLE
why the output name is ids folder?

### ISSUE THREAD

**Issue by m3m3-chan** [habrman/FaceRecognition#7]
hi!
I have a problem with showing the id name of the recognized faces. when the face is detected, the output name is the id folder name instead of the person id.
my ids folder path is as follows:  ids/x/x0.png
but what I get in the console is:   "Hi ids! Distance: 0.58" and the same name appears under the identified face.

thanks,

**Comment by jiulian** [comment]
I try to run the script and it displayed exactly the folder name that I set.

python main.py 20170512-110547/20170512-110547.pb ./ids/


Matches in frame:
Hi Johnson! Distance: 0.5655
Matches in frame:
Hi Johnson! Distance: 0.5174
Couldn't find a face

**Comment by habrman** [comment]
I just tried to set it up from scratch and it works for me as well. Can you please provide your exact folder structure and the command you use to run it all?

**Comment by m3m3-chan** [comment]
Hi Habrman, 
I followed the same folder structure you proposed. So in the code folder, I have the following:
/model
│   ├── model
/ids
│   ├── Adam
│   │   ├── Adam0.png
│   │   ├── Adam1.png
│   ├── Eve
│   │   ├── Eve0.png 

the command I use to run it: python main.py ./model/model.pb ./ids/

from playing around the code, I concluded that the problem lies in this line:
` self.id_names += [image_path.split('/')[-2]] * len(face_patches)`
turns out that the split function splits the paths in a way that it takes " Adam/Adam0.png" as one part. the last (/) in the path is not split.
I tried setting [-2] to [-1] & I get "Adam/Adam0.png" & when I tried [-0] (though it might not make any sense)  but it gave me "Adam0.png"

for more info, I am running the code on python 3.5 on Windows 10.

**Comment by m3m3-chan** [comment]
I solved this by changing the function! So instead of split() I use dirname() and change this  line: 
`self.id_names += [image_path.split('/')[-2]] * len(face_patches)`
 to `self.id_names += [os.path.dirname(image_path)[-1]] * len(face_patches)`

I think it's an issue with the backslash coz when I print the img_path I get this output: 
img_path=./ids/m\m2.png
though I'm still curious why it couldn't work well for me only :/

thanks anyway 👍 
EDIT: dirname() only doesn't solve the problem! I haven't noticed that coz I named all my id folders with 1 letter which is why dirname()[-1] worked so far (it gave me the last letter of the folder name)
 I used the split() with dirname()  and it's working well (tested it with long names this time):
`self.id_names += [ os.path.dirname(image_path).split('/')[-1]] * len(face_patches)`

**Comment by habrman** [comment]
What system do you use?

**Comment by m3m3-chan** [comment]
Windows 10 and running python 3.5  Anaconda

**Comment by habrman** [comment]
That explains it. I'll update the code to handle this as well

**Comment by m3m3-chan** [comment]
FYI, turns out it doesn't work with dirname() as I thought! 
I updated my  comment above & added the split to make it work.

**Comment by Ryiel** [comment]
it doesn't work in pycharm

**Comment by habrman** [comment]
Status update: I haven't spent any time on this but I will, one rainy day when I have nothing to do. This is due to how I handle paths in the code. I assume that the directories are separated by '/' but Windows uses '\' which breaks some logic. It's not a big fix that's required.

**Comment by alex-o98** [comment]
changing 
`self.id_names += [image_path.split('/')[-2]] * len(face_patches)`
to
```
path = os.path.dirname(image_path)
self.id_names += [os.path.basename(path)] * len(face_patches)
```
fixes the problem. This takes the name of the parent directory, instead of taking the name of the file and removing the last one/two numbers. This is better if you have a lot of pictures and you don't want to rename them.

It also works on both Linux and Windows (Based on habrman's last post)
